package me.a186.mvc.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_auth_group", "ids", AuthGroup.class);
		arp.addMapping("t_auth_group_access", "ids", AuthGroupAccess.class);
		arp.addMapping("t_auth_group_modules", "ids", AuthGroupModules.class);
		arp.addMapping("t_auth_group_rule", "ids", AuthGroupRule.class);
		arp.addMapping("t_auth_rule", "ids", AuthRule.class);
		arp.addMapping("t_modules", "ids", Modules.class);
		arp.addMapping("t_syslog", "ids", Syslog.class);
		arp.addMapping("t_user", "ids", User.class);
	}
}

