package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseAuthGroupRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthGroupRule extends BaseAuthGroupRule<AuthGroupRule> {
	public static final AuthGroupRule dao = new AuthGroupRule();
}
