package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseAuthGroupModules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthGroupModules extends BaseAuthGroupModules<AuthGroupModules> {
	public static final AuthGroupModules dao = new AuthGroupModules();
}
