package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseAuthGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthGroup extends BaseAuthGroup<AuthGroup> {
    public static final AuthGroup dao = new AuthGroup();

    /**
     * 分页Select
     */
    public static final String sqlId_splitPageSelect = "authGroup.splitPageSelect";

    /**
     * 分页from
     */
    public static final String sqlId_splitPageFrom = "authGroup.splitPageFrom";

    /**
     * 获取角色功能
     */
    public static final String sqlId_getRule = "authGroup.getRule";

    /**
     * 获取角色模块
     */
    public static final String sqlId_getModules = "authGroup.getModules";

    /**
     * 删除角色功能
     */
    public static final String sqlId_deleteRule = "authGroup.deleteRule";


    /**
     * 删除角色模块
     */
    public static final String sqlId_deleteModules = "authGroup.deleteModules";

    /**
     * 查询用户包含角色
     */
    public static final String sqlId_selectByUser = "authGroup.selectByUser";

    /**
     * 查询所有角色
     */
    public static final String sqlId_selectAll = "authGroup.selectAll";

    /**
     * 删除用户包含角色
     */
    public static final String sqlId_deleteByUser = "authGroup.deleteByUser";
}
