package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseAuthGroupAccess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthGroupAccess extends BaseAuthGroupAccess<AuthGroupAccess> {
	public static final AuthGroupAccess dao = new AuthGroupAccess();
}
