package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseModules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Modules extends BaseModules<Modules> {
    public static final Modules dao = new Modules();

    /**
     * 获取顶级模块
     */
    public static final String sqlId_getParents = "modules.getParents";


    /**
     * 分页Select
     */
    public static final String sqlId_splitPageSelect = "modules.splitPageSelect";

    /**
     * 分页from
     */
    public static final String sqlId_splitPageFrom = "modules.splitPageFrom";

    /**
     * 查询根节点
     */
    public static final String sqlId_rootNode = "modules.rootNode";
    /**
     * 根据上级节点id查询子节点信息
     */
    public static final String sqlId_childNode = "modules.childNode";

    /**
     * 查询用户拥有的二级菜单
     */
    public static final String sqlId_twoLevelMenu = "modules.twoLevelMenu";
}
