package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseSyslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syslog extends BaseSyslog<Syslog> {
	public static final Syslog dao = new Syslog();
}
