package me.a186.mvc.model;

import me.a186.mvc.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
	public static final UserInfo dao = new UserInfo();
}
