package me.a186.mvc.model.base;

import me.a186.mvc.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by PunkVv, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends BaseModel<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setErrorcount(java.lang.Long errorcount) {
		set("errorcount", errorcount);
	}

	public java.lang.Long getErrorcount() {
		return get("errorcount");
	}

	public void setOrderids(java.lang.Long orderids) {
		set("orderids", orderids);
	}

	public java.lang.Long getOrderids() {
		return get("orderids");
	}

	public void setPassword(byte[] password) {
		set("password", password);
	}

	public byte[] getPassword() {
		return get("password");
	}

	public void setSalt(byte[] salt) {
		set("salt", salt);
	}

	public byte[] getSalt() {
		return get("salt");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setStopdate(java.util.Date stopdate) {
		set("stopdate", stopdate);
	}

	public java.util.Date getStopdate() {
		return get("stopdate");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

}
