package me.a186.mvc.model.base;

import me.a186.mvc.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by PunkVv, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthGroup<M extends BaseAuthGroup<M>> extends BaseModel<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
